const buildImages = (folder, count, title) =>
  Array.from({ length: count }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    return {
      webp: `/images/webp/${folder}_${n}.webp`,
      png: `/images/${folder}_${n}.png`,
      alt: `${title} screenshot ${i + 1}`,
    };
  });

export const CODING_PROJECTS = [
  {
    id: 1,
    slug: "seapark-lss",
    title: "Seapark LSS",
    type: "Web App",
    description:
      "Management system for a sea park. Crew, departments (Dolphins, Sea Lions, Seals, Aquasplash), tasks and water quality measurements are tracked centrally through dashboards and notifications.",
    info: "You can login to all users with pin '0000'",
    cover: "/images/thumbnails/seapark.jpg",
    alt: "Seapark LSS dashboard with departments overview",
    images: buildImages("bwd_seapark", 9, "Seapark LSS"),
    web: "https://boudewijnseapark-server.onrender.com/",
    technologies: ["EJS", "Express", "Knex", "Objection.js", "SQLite", "bcrypt", "CSS", "JavaScript"],
  },
  {
    id: 2,
    slug: "roomcraft",
    title: "RoomCraft",
    type: "Configurator",
    description:
      "3D room configurator that lets users draw a room, add furniture and instantly preview the result in 3D, from blueprint to perspective view.",
    info: "You can create a new user and try out the app",
    cover: "/images/thumbnails/roomcraft.jpg",
    alt: "RoomCraft landing page",
    images: buildImages("configurate3D", 9, "RoomCraft"),
    web: "https://afstudeerproject-lito00356.onrender.com/",
    technologies: [
      "React",
      "Vite",
      "Three.js",
      "React Three Fiber",
      "Drei",
      "Supabase",
      "React Query",
      "React Router",
      "React Hook Form",
    ],
  },
  {
    id: 3,
    slug: "kanbanana",
    title: "Kanbanana",
    type: "Web App",
    description:
      "Kanban board for project management with To Do, In Progress, Ready For Review and Done columns, a backlog overview and task cards with tags and descriptions.",
    info: "Play with current set up projects or add a new one",
    cover: "/images/thumbnails/kanbanana.jpg",
    alt: "Kanbanana board with tasks",
    images: buildImages("kanbanana", 5, "Kanbanana"),
    web: "https://kanbanana-r1kw.onrender.com/",
    technologies: ["React", "Strapi", "CSS"],
  },
  {
    id: 4,
    slug: "tracking-marker",
    title: "Tracking Marker",
    type: "Web App",
    description:
      "Personal task tracker with categories such as Work, Hobby and Home, pending/done overviews and a login system so you can keep track from anywhere.",
    info: "You can create a new user for this app",
    cover: "/images/thumbnails/todo.jpg",
    alt: "Tracking Marker task overview",
    images: buildImages("tracking_marker", 7, "Tracking Marker"),
    web: "https://todo-app-eydb.onrender.com/",
    technologies: ["EJS", "Express", "Knex", "Objection.js", "SQLite", "bcrypt", "JWT", "JavaScript"],
  },
  {
    id: 5,
    slug: "foosball",
    title: "Foosball",
    type: "Native App",
    description:
      "Companion app for the foosball table: keep score, log matches and a small leaderboard. Still in development, screenshots coming soon.",
    cover: "/images/thumbnails/foosball.jpg",
    alt: "Foosball app calendar with matches",
    images: buildImages("foosball", 7, "Foosball"),
  },
];

export const VFX_PROJECTS = [
  {
    id: 1,
    title: "John Wick 4",
    type: "Movie",
    description: "Action movie about John Wick",
    image: "/images/webp/john_wick4.webp",
    alt: "John Wick 4 movieposter",
    imdb: "https://www.imdb.com/title/tt10366206/",
  },
  {
    id: 2,
    title: "Heart Of Stone",
    type: "Movie",
    description: "Action movie about a spy",
    image: "/images/webp/heart_of_stone.webp",
    alt: "Heart of Stone movieposter",
    imdb: "https://www.imdb.com/title/tt13603966/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_heart%20of%20stone",
  },
  {
    id: 3,
    title: "Freaks Out",
    type: "Movie",
    description: "Science-fiction and superpowers in WWII",
    image: "/images/webp/freaks_out.webp",
    alt: "Freaks Out movieposter",
    imdb: "https://www.imdb.com/title/tt7270808/?ref_=fn_t_1",
  },
  {
    id: 4,
    title: "Vesper",
    type: "Movie",
    description: "A lost world where food is scarce! Thrilling sci-fi and great visuals",
    image: "/images/webp/vesper.webp",
    alt: "Vesper movieposter",
    imdb: "https://www.imdb.com/title/tt20225374/?ref_=nv_sr_srsg_0_tt_4_nm_4_in_0_q_vesper",
  },
  {
    id: 5,
    title: "The Witcher Season 3",
    type: "Series",
    description: "Series about Geralt Of Rivia trying to find his ward from the law of surprise",
    image: "/images/webp/the_witcher.webp",
    alt: "The Witcher season 3 series poster",
    imdb: "https://www.imdb.com/title/tt5180504/?ref_=nv_sr_srsg_0_tt_6_nm_1_in_1_q_the%20witcher",
  },
  {
    id: 6,
    title: "Le Jardinier",
    type: "Movie",
    description: "Muscles from Brussels are back! Comedy packed with humor and nostalgia",
    image: "/images/webp/le_jardinier.webp",
    alt: "Le Jardinier movieposter",
    imdb: "https://www.imdb.com/title/tt30973842/?ref_=fn_t_1",
  },
  {
    id: 7,
    title: "More will be added soon",
    type: "Soon",
    description: "The rest of my work will soon be visible!",
    image: "https://placehold.co/400x600/090109/e2e2e2?text=More+Soon",
    alt: "Placeholder for upcoming VFX projects",
    imdb: "",
  },
];
