export const PROJECTS = [
  {
    id: 1,
    title: "John Wick 4",
    type: "Movie",
    description: "Action movie about John Wick",
    image: "/images/webp/john_wick4.webp",
    alt: "John Wick 4 movieposter",
  },
  {
    id: 2,
    title: "Heart Of Stone",
    type: "Movie",
    description: "Action movie about a spy",
    image: "/images/webp/heart_of_stone.webp",
    alt: "Heart of Stone movieposter",
  },
  {
    id: 3,
    title: "Freaks Out",
    type: "Movie",
    description: "Science-fiction and superpowers in WWII",
    image: "/images/webp/freaks_out.webp",
    alt: "Freaks Out movieposter",
  },
  {
    id: 4,
    title: "Vesper",
    type: "Movie",
    description: "A lost world where food is scarce! Thrilling sci-fi and great visuals",
    image: "/images/webp/vesper.webp",
    alt: "Vesper movieposter",
  },
  {
    id: 5,
    title: "The Witcher Season 4",
    type: "Series",
    description: "Series about Geralt Of Rivia trying to find his ward from the law of surprise",
    image: "/images/webp/the_witcher.webp",
    alt: "The Witcher season 4 series poster",
  },
  {
    id: 6,
    title: "Le Jardinier",
    type: "Movie",
    description: "Muscles from Brussels are back! Comedy packed with humor and nostalgia",
    image: "/images/webp/le_jardinier.webp",
    alt: "Le Jardinier movieposter",
  },
];
